docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
   - docker:dind
  before_script:
    - docker login -u "falagheband" -p "ftmal3922"
  script:
    - docker build -t falagheband/ie_frontend .
    - docker push falagheband/ie_frontend
  after_script:
    - docker logout  
  only:
    - master