docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
   - docker:dind
  before_script:
    - docker login -u "falagheband" -p "ftmal3922"
  script:
    - docker build -t myapp .
    - docker push falagheband/ie_frontend
  only:
    - master